# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "web/assets"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "web/resources/**/*"
    - "!web/resources/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "web/vendor/foundation-sites/scss"
    - "web/vendor/motion-ui/src"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    # Libraries requried by Foundation
    - "web/vendor/jquery/dist/jquery.js"
    - "web/vendor/what-input/what-input.js"
    # Core Foundation files
    - "web/vendor/foundation-sites/js/foundation.core.js"
    - "web/vendor/foundation-sites/js/foundation.util.*.js"
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    - "web/vendor/foundation-sites/js/foundation.abide.js"
    - "web/vendor/foundation-sites/js/foundation.accordion.js"
    - "web/vendor/foundation-sites/js/foundation.accordionMenu.js"
    - "web/vendor/foundation-sites/js/foundation.drilldown.js"
    - "web/vendor/foundation-sites/js/foundation.dropdown.js"
    - "web/vendor/foundation-sites/js/foundation.dropdownMenu.js"
    - "web/vendor/foundation-sites/js/foundation.equalizer.js"
    - "web/vendor/foundation-sites/js/foundation.interchange.js"
    - "web/vendor/foundation-sites/js/foundation.magellan.js"
    - "web/vendor/foundation-sites/js/foundation.offcanvas.js"
    - "web/vendor/foundation-sites/js/foundation.orbit.js"
    - "web/vendor/foundation-sites/js/foundation.responsiveMenu.js"
    - "web/vendor/foundation-sites/js/foundation.responsiveToggle.js"
    - "web/vendor/foundation-sites/js/foundation.reveal.js"
    - "web/vendor/foundation-sites/js/foundation.slider.js"
    - "web/vendor/foundation-sites/js/foundation.sticky.js"
    - "web/vendor/foundation-sites/js/foundation.tabs.js"
    - "web/vendor/foundation-sites/js/foundation.toggler.js"
    - "web/vendor/foundation-sites/js/foundation.tooltip.js"
    # Runalyze App Scripts
    - "lib/jquery.form.js"
    - "lib/jquery.metadata.js"
    - "lib/jquery.tablesorter-2.18.4.js"
    - "lib/jquery.tablesorter-2.18.4.pager.js"
    - "lib/bootstrap-tooltip.js"

    - "lib/fineuploader-3.5.0.min.js"

    - "lib/jquery.datepicker.js"
    - "lib/jquery.chosen.min.js"

    - "lib/runalyze.lib.js"
    - "lib/runalyze.lib.plot.js"
    - "lib/runalyze.lib.plot.options.js"
    - "lib/runalyze.lib.plot.saver.js"
    - "lib/runalyze.lib.plot.events.js"
    - "lib/runalyze.lib.tablesorter.js"
    - "lib/runalyze.lib.log.js"
    - "lib/runalyze.lib.options.js"
    - "lib/runalyze.lib.config.js"
    - "lib/runalyze.lib.overlay.js"
    - "lib/runalyze.lib.panels.js"
    - "lib/runalyze.lib.databrowser.js"
    - "lib/runalyze.lib.statistics.js"
    - "lib/runalyze.lib.training.js"
    - "lib/runalyze.lib.feature.js"

    - "lib/flot-0.8.3/base64.js"
    - "lib/flot-0.8.3/jquery.flot.min.js"
    - "lib/flot-0.8.3/jquery.flot.resize.min.js"
    - "lib/flot-0.8.3/jquery.flot.selection.js"
    - "lib/flot-0.8.3/jquery.flot.crosshair.js"
    - "lib/flot-0.8.3/jquery.flot.navigate.min.js"
    - "lib/flot-0.8.3/jquery.flot.hiddengraphs.js"
    - "lib/flot-0.8.3/jquery.flot.stack.js"
    - "lib/flot-0.8.3/jquery.flot.textLegend.js"
    - "lib/flot-0.8.3/jquery.flot.orderBars.js"
    - "lib/flot-0.8.3/jquery.flot.canvas.js"
    - "lib/flot-0.8.3/jquery.flot.time.min.js"
    - "lib/flot-0.8.3/jquery.flot.curvedLines.js"

    - "web/vendor/leaflet/dist/leaflet.js"
    - "lib/leaflet/runalyze.leaflet.js"
    - "lib/leaflet/runalyze.leaflet.layers.js"
    - "lib/leaflet/runalyze.leaflet.routes.js"

    - "web/vendor/fontIconPicker/jquery.fonticonpicker.js"
    # Paths to your own project code are here
    - "web/resources/js/!(app).js"
    - "web/resources/js/app.js"
