knpu_oauth2_client:
     clients:
         tomtom:
             type: generic
             provider_class: \League\OAuth2\Client\Provider\TomTomMySports
             client_id: %tomtom_mysports_client_id%
             client_secret: %tomtom_mysports_client_secret%
             redirect_route: connect_tomtom_mysports_check
             redirect_params: {}